# Generated by Django 3.1.7 on 2021-03-12 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proj',
            old_name='projName',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='proj',
            name='projDescription',
        ),
        migrations.AddField(
            model_name='proj',
            name='budjet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proj',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proj',
            name='project_type',
            field=models.CharField(choices=[('IT', 'IT'), ('Technology', 'Technology'), ('Coffe Shops', 'Coffe Shops'), ('Manufacturing', 'Manufacturing'), ('Media', 'Media')], default='it', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proj',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
