# Generated by Django 3.1.7 on 2021-03-13 11:17

from django.db import migrations, models
import proj.models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=proj.models.image_upload),
        ),
    ]
